### PR TITLE
Initial manual commit of doxygen-generated documentation

### PR DESCRIPTION
**Pull request by cjbackhouse**
I have scripting that automatically generates this documentation. The idea would be to run it nightly(?) in a cron-job, push to this branch, and merge into master in an automated way.

### CODE REVIEW

**Comment by cjbackhouse** [comment]
I am currently indexing
larsim larreco larcoreobj larcorealg lardataalg lardataobj larsoftobj larwirecell larpandora larg4 larexamples lareventdisplay larcore lardata larevt larana larsoft webevd larutils larbatch larpandoracontent, sbnobj sbncode sbndcode icaruscode icarusalg sbndutil sbnanaobj sbnana
Probably there are more things that ought to be added

**Comment by PetrilloAtWork** [comment]
I have to think of a good way to review this.
An alternative proposal is that this script be run only on every _release_, and the result saved for good.

**Comment by henrylay97** [comment]
First off great that this is being done! 

I've started to have a look, clearly not an obvious thing to review. First impressions are that a lot of the linking seems to need work, for example on the index page only larg4 seems to take you anywhere. Is that something that has to be gone through manually? 

I also noticed some misplacing where it describes fcl parameters as functions etc (see sbndcode's AnalysisTree for an example). Finally I had a quick look at sbnanaobj's StandardRecord (which would be hugely useful to have documentation for people playing with caf structure for the first time). At the moment nothing seems to be automatically generated, I take it that a fair amount of commenting of the source code would be needed for this?

**Comment by cjbackhouse** [comment]
The review request isn't really targeted at the doxygen output itself. Yes, I can improve the front page, I'm not sure what doxygen will make of fcl, but maybe there's some way to improve the situation, and StandardRecord comments will need to be encouraged and ensured to be in standard format.

I'm really asking about the concept of having something like this, and of automatically generating and merging it on some schedule (daily/weekly?).

I can try and set up the scripting and have it commit to this branch, and then we can check if we like the kind of commits it makes, and if we're happy to have it merged without manual intervention. I'm not sure if the permissions will allow that, but hopefully we can make some special user or special case for this directory to allow that.

**Comment by cjbackhouse** [comment]
I will also add the actual scripting (which is currently a mess) and some instructions in case someone else wants to be in charge of the cron job (please!).

**Comment by PetrilloAtWork** [comment]
My scripting for [`icaruscode`](https://github.com/SBNSoftware/icaruscode/tree/develop/doc) is also adding some metadata which I think important to track, including also the Doxygen configuration file (which I would also like to take a look at as part of the "review").

**Comment by cjbackhouse** [comment]
Interesting. Maybe we can make some effort to merge the two implementations. You have definitely taken more care with the front page and styling etc.

**Comment by PetrilloAtWork** [comment]
GitHub interface can't cope well with this amount of files.
Would you try using: `CREATE_SUBDIRS = YES` to ease its work? Although Doxygen promises 4096 directories, which might still be too much for GitHub.

**Comment by PetrilloAtWork** [comment]
I should also point out that sticking to a specific version rather than `develop` is a pain.
Basically I needed to run on a GPVM to use UPS and get the matching versions of everything.
I used `ups setup` for that; it may be possible to use `ups depend` on a CVMFS-aware place with proper UPS override hacks so that we are not necessarily confined on GPVM, but GPVM are the easiest solution.

**Comment by PetrilloAtWork** [comment]
:heavy_check_mark: I did not render the tree, but it looks like formulas are correctly rendered (which did not happen when running Doxygen on `icarusgpvm04`).
Rendering them as SVG instead of PNG may be an interesting alternative (`HTML_FORMULA_FORMAT = svg`), but it requires Inkscape to be present.

**Comment by PetrilloAtWork** [comment]
> GitHub interface can't cope well with this amount of files. Would you try using: `CREATE_SUBDIRS = YES` to ease its work? ~Although Doxygen promises 4096 directories, which might still be too much for GitHub.~ Actually Doxygen promises these 4096 directories _in two levels_, so it might be ok.

I see that actually `CREATE_SUBDIRS` is set to `YES`, but the commit appears to have _both_ the flattened and tree structure? May it be that you forgot to remove the output directory and start from clean?

**Comment by cjbackhouse** [comment]
Updated, hopefully properly. github is still very unhappy. I think you will just have to work locally with actual git.

I am a bit worried about the file size, currently 800MB, and github pages promises a limit of 1GB. I don't know if there's some specific code I'm indexing that is very large and that we could safely skip. Trying to minify the html didn't help very much.

**Comment by cjbackhouse** [comment]
These last (trivial) commits were made by a cron job, so I think all the mechanics of this is working.

**Comment by cjbackhouse** [comment]
`HTML_FORMULA_FORMAT` didn't seem to have any effect. Presumably a too-old doxygen or inkscape install at UCL.

**Comment by PetrilloAtWork** [comment]
I have opted for relying on 3rd party there; not sure if it's smart.
Basically for formulas it writes a coded formula and relies on a style to render it. Rendering is nowhere as beautiful as LaTeX.
I am compiling my own version of Doxygen (1.9.4) to make that work though, since a bug was solved only recently.

**Comment by cjbackhouse** [comment]
As you can see, the scripting is setup to update it nightly, which I think is also my preference. I would like to merge this once manually so we can take a proper look at it, and then update the scripting so that it automatically tries to merge every night.

**Review by henrylay97 — APPROVED** [review]
Apologies for the delay on this. I think this clearly works as a first pass so I'd say lets get it in. There are open questions on where to host the script but that's outside of my wheelhouse really. It is only once it is up and working that people can use it and notice where comments need changing/updating in order to be useful!

Thanks Chris!

**Pull request merged**
