### PR TITLE
checkRawFilesOnlineStatus.sh supports runs >10k and saves file lists

### PR DESCRIPTION
**Pull request by PetrilloAtWork**

### CODE REVIEW

**Review by mayawos — APPROVED** [review]
looks good to me. Thanks for the additional features!

**Comment by wesketchum** [comment]
@PetrilloAtWork can this be made into non-draft PR and merged in?

**Comment by PetrilloAtWork** [comment]
Nope, needs a fix. I broke the functionality of asking for stream `*`.
And I haven't yet gotten to a satisfactory solution.

**Comment by PetrilloAtWork** [comment]
Became obsolete.

**Pull request closed without merging**
